name: Deploy Docker Image to Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to DigitalOcean Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Logging into server..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hw-assignment4:latest
            
            echo "Stopping and removing old container..."
            docker stop hw-assignment4 || true
            docker rm hw-assignment4 || true
            
            echo "Running new container..."
            docker run -d --name hw-assignment4 -v /opt/assignment_outputs:/app/data ${{ secrets.DOCKERHUB_USERNAME }}/hw-assignment4:latest
