name: Deploy Docker Image to Server

on:
  push:
    branches:
      - prod  # ✅ Triggers deployment only on "prod" branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Latest Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hw-assignment4:latest

      - name: Deploy to DigitalOcean Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop hw-assignment4 || true
            docker rm hw-assignment4 || true
            docker run -d -p 8000:8000 --name hw-assignment4 \
              -v /opt/assignment_outputs:/app/data \
              ${{ secrets.DOCKERHUB_USERNAME }}/hw-assignment4:latest
